### ISSUE TITLE
WindowsError: [Error 5] Access is Denied - When Attempting to Call Caffe Executable from Digits

### ISSUE THREAD

**Issue by jonathancurrie** [NVIDIA/DIGITS#1095]
Hi,

As best as I can I have followed the instructions here:
https://github.com/NVIDIA/DIGITS/blob/master/docs/BuildDigitsWindows.md

when attempting to use DIGITS + Caffe under Win7 x64. I've successfully compiled Caffe using VS2013 and verified it is working correctly from the command line and C++. I've also set up Python (2.7.11 x64) as close as possible to the instructions, screenshot of pip list at the bottom, in order to start using DIGITS. However I just can't get DIGITS to successfully call the caffe.exe executable - it always complains of access denied from the subprocess.Popen method (roughly line 217 in task.py), as per the below screenshots.

I've troubleshooted all evening to get around this - but I'm not having any luck. No combinations of administrator access, removing UAC, powershell usage or newer versions of packages has fixed this. Note I have also inserted `return '0.0.3'` on line 157 in caffe_option.py so I could at least get the DIGITS server to start - otherwise it fails simply trying to read the executable version number (same error).

Has anyone else come across this, or have any suggestions on how to work around it? I suspect it is due to it running as a server application.. but can't work out how to elevate the permissions correctly.

I'm simply following this example:
[https://github.com/NVIDIA/DIGITS/blob/master/docs/GettingStarted.md](url)
data generation worked without issue, model is the issue...

Thanks!
Jonathan
![windigits](https://cloud.githubusercontent.com/assets/4051369/18668156/fee67d08-7f87-11e6-8c00-f058fffbb11b.png)
![winerr5](https://cloud.githubusercontent.com/assets/4051369/18668116/b535e95a-7f87-11e6-9116-b71238061c0a.png)
![winlist](https://cloud.githubusercontent.com/assets/4051369/18668121/ba44e310-7f87-11e6-9f4e-3266f97db0e6.png)

**Comment by IsaacYangSLA** [comment]
@jonathancurrie , your environment is pretty similar to what I have, and I haven't seen that issue.  Mine is Win7 Pro x64, so that might be different.

However, you mentioned your Caffe build didn't return version string so you needed to modify caffe_option.py.  Can you help try the following:
1.  run caffe.exe -version inside cmd.exe and see if it returns "CAFFE_VERSION" or something like 1.0.0-rc3.  The Windows branch in BVLC caffe should return a meaningful version string.
2.  in a regular cmd.exe, and in some arbitrary directory, run the subprocess args you saw on the screen, like c:\dev\caffe\caffe-master\Build\x64\Release\build\tools\caffe train --solver=c:\dev\digits\<SKIP> ... ...  This will basically run caffe without DIGITS.
3. in the same regular cmd.exe, launch your DIGITS.

Because your path to caffe includes caffe-master and build directory seems different from the one specified in VS2013 solution, you might use BVLC master branch with your own configuration.

**Comment by jonathancurrie** [comment]
Hi Issac, many thanks for your reply.

I should have mentioned I tried (2) but in Python using subprocess as per the below python script (renamed .txt):
[test_popen_caffe.txt](https://github.com/NVIDIA/DIGITS/files/486995/test_popen_caffe.txt)

and this works fine:
![winmanual](https://cloud.githubusercontent.com/assets/4051369/18744605/cf9d8cd0-8112-11e6-865b-d7deaf8f07d4.png)

This to me showed that caffe was working correctly, as was subprocess + python?

Also tried (3) (no admin access, no powershell, regular cmd), same denied error.

Re (1) - I modified the source of caffe so it didn't return "CAFFE_VERSION" during compilation. I'm guessing I may have downloaded the wrong caffe branch somehow, I will have another go soon and update.

**Comment by IsaacYangSLA** [comment]
@jonathancurrie , thanks for the updates.  We tried DIGITS on Windows Server a few months ago and didn't see such behavior.  The only possible reasons that I could think of are:
1.  Anti-virus is checking that folder immediately after it is created, and that causes Access Denied (however, it should not always fail...)
2.  The caffe executable path is not found correctly.  I saw from the log caffe path is under Build\x64\Release\build\tools, which is Linux build process convention.  On the other hand, Windows branch of BVLC caffe put caffe.exe under Build\x64\Release.  This matches the path in your test_popen_caffe.txt.  Can you try to set your PATH to include c:\dev\caffe\caffe-master\Build\x64\Release (not the build\tools one)?  One stackoverflow post mentioned if the first argument of subprocess.popen did not point to an existing file, the error was Access Denied.
3.  I don't think this is the case, but is that folder a network-mounted share?  Some NAS might report access denied if the folder is created and files are written into it immediately.

**Comment by jonathancurrie** [comment]
Thanks again for your prompt reply. I'm just about to try build caffe again from the BVLC windows branch, but answers to the above (still not working):

1. Norton disabled, no difference
2. Relevant PATH entries: 
`C:\dev\graphviz\bin;C:\Python27_x64\;C:\Python27_x64\Scripts;C:\dev\caffe\caffe-master\Build\x64\Release;`
3. No, just local C drive.

Will try a caffe rebuild now.

**Comment by jonathancurrie** [comment]
Hi, sorry I can't work out which version I should be downloading. I've cloned this one:
[https://github.com/BVLC/caffe/tree/windows](url)

but it results in all sorts of compilation errors (missing NaN propagation mode, incompatible cudnn calls...), and I still can't find where CAFFE_VERSION is defined in this project.

If I download the latest release from:
[https://github.com/BVLC/caffe/releases](url)

there is no windows directory. What am I missing here?

BTW I should clarify I am on Win 7 Pro x64 too, I meant that DIGITS is running as a server, so perhaps that has different permissions?

**Comment by lukeyeager** [comment]
My guess is they probably just broke something in the `windows` branch then.

**Comment by IsaacYangSLA** [comment]
Give me some time.  I will try to build the latest Windows branch of BVLC locally.

**Comment by jonathancurrie** [comment]
Many thanks!


-------- Original message --------

**Comment by IsaacYangSLA** [comment]
@jonathancurrie , I tried the latest caffe windows branch and also got the same issue.  However, the build process on the same codes seemed working ok with cuda 7.5 w/ cudnn 4.0.  Can you try that on your side?  I will try to find time investigating why other configurations failed.

**Comment by lukeyeager** [comment]
@willyd: any suggestions?

**Comment by willyd** [comment]
@lukeyeager I haven't played a lot with DIGITS so I can't tell what's wrong here. I haven't made any changes to the windows branch yet so maybe the previous maintainers could give better advice. I am still making some changes to my own fork of caffe to make the CMake build working on windows before pushing them to BVLC/windows. Once that is done, I will check if I can repro this issue. I know that @lunzueta as played with DIGITS on Windows, maybe he has some insight.

**Comment by lukeyeager** [comment]
@willyd Ok - thanks for the quick response!

**Comment by lunzueta** [comment]
Hi @jonathancurrie . I'm not sure what the problem might be (I didn't have that problem in my tests on Windows 10), but just in case, the first thing I'd check is the installed Caffe version, because as you know, there are different, let's say, not-so-stable-yet Windows versions of Caffe. Some of them when the command 'caffe -version' is run in the console don't show a version that DIGITS understands correctly. So, the first thing to do is to check whether this command runs properly in the console from any folder (as it should be accessible from the PATH environment variable). Currently, it should give the following feedback: "caffe version 1.0.0-rc3".

Just in case, I recommend you to use @willyd's [Caffe version](https://github.com/willyd/caffe/tree/windows-cmake)

Alternatively, you might also try some other, derived from it, like [this](https://github.com/lunzueta/caffe/tree/windows-cmake-ms) of mine, which is a fusion between [Microsoft's fork](https://github.com/microsoft/caffe) and @willyd's, which also contains [DetectNet](https://github.com/NVIDIA/DIGITS/tree/master/examples/object-detection) (I've already been able to run it on Windows 10).

Anyway, be aware of the last [updates](https://github.com/BVLC/caffe/pull/3990) that will take place in the official Caffe's Windows version in the near future, which will help to get a more stable version.

The second thing I'd do is to check where the DIGITS folder was installed. It shouldn't be installed in a folder where you need administrative access rights, like "C:\Program Files", "C:\Program Files (x86)", etc

**Comment by jonathancurrie** [comment]
Hi everyone,

Many thanks for your ideas and suggestions. I persisted with the idea that the problem was due to a permissions error with Python, rather than Caffe/DIGITS, and eventually I found a "fix". Within DIGITS, in caffe_option.py line 158 (or so) is the initial call to the Caffe executable to read the version string, via subprocess.Popen. Adding the option "shell=True" to this call fixed the permissions error, and now I can succesfully train models. Reading the documentation [(https://docs.python.org/2/library/subprocess.html)](url) suggests I shouldn't need this, but for some reason just adding it here fixed everything...

Anyway, as a summary, I have now working:
- Microsoft Caffe [(https://github.com/Microsoft/caffe)](url)
- cuDNN 5.1.3
- DIGITS 4.1-dev [(https://github.com/NVIDIA/DIGITS)](url)
- CUDA Toolkit 7.5.17
- Python 2.7.11 x64

All under Win7 Pro. I've just successfully trained the LeNet model over the MNIST data and looks to be working pretty well! 

As an aside, I never worked out the cause of why I can't see CAFFE_VERSION defined anywhere in any of the branches I downloaded (whether Microsoft, BVLC or willyd), but I did accidentally have a newer version of cuDNN than I realised (sorry guys, probably the reason why the BLVC windows branch didn't build).

Once again, thank you for all the support received - you guys are awesome!

Jonathan

**Comment by lukeyeager** [comment]
> Adding the option "shell=True" to this call fixed the permissions error, and now I can succesfully train models.

Weird. I wouldn't have guessed that would make a difference. Glad you found a workaround. Please report back if you find any more information about this error.
