### ISSUE TITLE
Error when running visualization of network in DIGITS5.1-dev

### ISSUE THREAD

**Issue by StevenPuttemans** [NVIDIA/DIGITS#1534]
Training and testing with models runs just fine. Even adapting the network with other layers works fine. However, at whatever stage, if I click the visualization button for the adapted model, I get the following error output:

```
500: INTERNAL SERVER ERROR
AttributeError
'int' object has no attribute '_values'
```

I have tried installing the graphviz library (which I guess is the backend used here) using `sudo apt-get install libgraphviz-dev` but that did not solve the issue.

Steps to reproduce in my case

- Create a new classification model
- At the standard LeNet/AlexNet network, click customize
- Then hit the visualize button

**Comment by lukeyeager** [comment]
I can't reproduce this. Can you run in debug mode (`digits-devserver --debug`) and see if you get a stacktrace?

**Comment by StevenPuttemans** [comment]
I will do so tomorrow at work and get back to you on this!

**Comment by StevenPuttemans** [comment]
@lukeyeager I ran in debug, the stacktrace retrieved is 

```
Traceback (most recent call last):
  File "/home/spu/.local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/spu/.local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/spu/Github/DIGITS/digits/webapp.py", line 81, in decorated
    return f(*args, **kwargs)
  File "/home/spu/Github/DIGITS/digits/model/views.py", line 126, in visualize_network
    ret = fw.get_network_visualization(flask.request.form['custom_network'])
  File "/home/spu/Github/DIGITS/digits/frameworks/caffe_framework.py", line 145, in get_network_visualization
    caffe.draw.draw_net(net, 'UD').encode('base64') +
  File "/home/spu/Github/caffe/python/caffe/draw.py", line 223, in draw_net
    return get_pydot_graph(caffe_net, rankdir, phase=phase).create(format=ext)
  File "/home/spu/Github/caffe/python/caffe/draw.py", line 167, in get_pydot_graph
    node_label = get_layer_label(layer, rankdir)
  File "/home/spu/Github/caffe/python/caffe/draw.py", line 107, in get_layer_label
    layer.pooling_param.kernel_size[0] if len(layer.pooling_param.kernel_size._values) else 1,
AttributeError: 'int' object has no attribute '_values'
```

**Comment by StevenPuttemans** [comment]
Okay with the stacktrace I found the issue. It seems that this is a problem in CAFFE, where someone tried to fix the drawing of the nets in this [PR](https://github.com/BVLC/caffe/commit/db6cf0a728cad63c93b345f2203f3ad1f5d5c2f4).

**Comment by StevenPuttemans** [comment]
Okay so the solution is quite straightforward, simply reverting back the changes in the draw.py file.

So to solve this, replace in draw.cpp

```
layer.pooling_param.kernel_size[0] if len(layer.pooling_param.kernel_size._values) else 1,
seperator,
layer.pooling_param.stride[0] if len(layer.pooling_param.stride._values) else 1,
seperator,
layer.pooling_param.pad[0] if len(layer.pooling_param.pad._values) else 0)
```

by

```
layer.pooling_param.kernel_size,
seperator,
layer.pooling_param.stride,
seperator,
layer.pooling_param.pad)
```

And the digits visualization button works again as before!

**Comment by lukeyeager** [comment]
Thanks for tracking it down! You might want to ping Evan for a fix on https://github.com/BVLC/caffe/pull/5010.

**Comment by IvyGongoogle** [comment]
@StevenPuttemans  nice notice
