### ISSUE TITLE
Unable to visualize model: "AttributeError"

### ISSUE THREAD

**Issue by DreSimpelo** [NVIDIA/DIGITS#591]
When I click on visualize, I get this error:

> 500: INTERNAL SERVER ERROR
> AttributeError
> 'google.protobuf.pyext._message.RepeatedScalarConta' object has no attribute '_values'

This happens to any model I try to visualize (LeNet, AlexNet, etc).

I have libprotoc version 2.6.0
> ~:>>protoc --version
> libprotoc 2.6.0

I also have pydot2 1.0.33
> ~:>>pip list | grep -i dot
pydot2 (1.0.33)

**Comment by wenwei202** [comment]
I have the same problem, did you figure out? @DreSimpelo

**Comment by mjohn123** [comment]
@wenwei202  Let removed the "._values" on lines 94,96,98 in python/caffe/draw.py. Looks like it wants to get the length of the array. I worked by remove them

**Comment by chunjy92** [comment]
The above solution is fine, but note  [this](https://github.com/NVIDIA/caffe/issues/303).
In short, you could consider installing the lower version of protobuf that doesn't complain about the issue. i.e.
`pip install protobuf==2.6.1`

**Comment by IvyGongoogle** [comment]
@chunjy92 it does not work for me using  `protobuf==2.6.1`. Instead, `protobuf==3.1.0` works for me.

**Comment by ToruHironaka** [comment]
Thanks your post @IvyGongoogle, I had the same problem but I could solve the problem after update protobuf to 3.1.0 from 2.6.1. I use pytho3.5.
